### ISSUE TITLE
Imagem grande em post destacado fica borrada

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/guarani#14]
No widget de Post de uma Categoria, imagem com uma grande dimensão estão ficando borradas.
Estas, abaixo, têm 2490 × 1758 e 2M.

![imagemdestacada](https://cloud.githubusercontent.com/assets/2422926/7543363/1f063110-f59a-11e4-8b82-faa55c063e39.png)
![imagemwidgetjosete](https://cloud.githubusercontent.com/assets/2422926/7543366/232b9c80-f59a-11e4-804d-4a1880e564bc.png)

**Comment by eduardozulian** [comment]
@anapaulabrasa, tentaram diminuir a imagem?

**Comment by anapaulabrasa** [comment]
Nossa! Nem lembro como resolvemos isso, mas resolvemos... Puxa, deveria ter fechado na época isso = /

**Comment by eduardozulian** [comment]
Perfeito! Vou fechar aqui.
